### ISSUE TITLE
Truncated sample data

### ISSUE THREAD

**Issue by 4piggies4me** [beddit/beddit-api#1]
The data returned from session.sampled_tracks.normal.data_url seems to be truncated: the size of the data is only half of the time aligned to 2 bytes (uint16), and the size is too small for 140Hz sampling from start_timestamp to end_timestamp.

**Comment by mikkow** [comment]
Hi, is this issue only related to one measurement, or does it happen more often? We have not noticed this kind of issue. You can also contact me privately with your user id, and what particular night was that measured: mikko@beddit.com.
